export const sampleProviders = [
  {
    id: '1',
    name: 'BhuMeet Spraying Services',
    latitude: 19.9526,
    longitude: 79.2961,
    city: 'Chandrapur',
    state: 'Maharashtra',
  },
  {
    id: '2',
    name: 'GreenField Agro Solutions',
    latitude: 20.5937,
    longitude: 78.9629,
    city: 'Nagpur',
    state: 'Maharashtra',
  },
  {
    id: '3',
    name: 'AgroTech Drones',
    latitude: 21.1458,
    longitude: 79.0882,
    city: 'Wardha',
    state: 'Maharashtra',
  },
  {
    id: '5',
    name: 'CropCare Services',
    latitude: 20.4275,
    longitude: 79.0414,
    city: 'Yavatmal',
    state: 'Maharashtra',
  },
  {
    id: '6',
    name: 'Desert Drones',
    latitude: 26.9124,
    longitude: 75.7873,
    city: 'Jaipur',
    state: 'Rajasthan',
  },
  {
    id: '7',
    name: 'Capital Crop Care',
    latitude: 28.6139,
    longitude: 77.209,
    city: 'Delhi',
    state: 'Delhi',
  },
  {
    id: '8',
    name: 'Karnataka Agro Services',
    latitude: 12.9716,
    longitude: 77.5946,
    city: 'Bangalore',
    state: 'Karnataka',
  },
  {
    id: '9',
    name: 'UP Farming Solutions',
    latitude: 26.8467,
    longitude: 80.9462,
    city: 'Lucknow',
    state: 'Uttar Pradesh',
  },
];